### ISSUE TITLE
Metadata don't work

### ISSUE THREAD

**Issue by MarcosPer** [emersion/mpris-service#12] opened 2017-08-20 09:16 UTC
I'm using this module and it works, it show player controls in https://github.com/azdyb/gnome-shell-extension-mpriscontrol and events are working but i can't send any metadata. I tried to update to node-dbus to 1.0.0 version following this https://github.com/Shouqun/node-dbus/blob/master/MIGRATING.md but it still failing.

How can i do for solve this?

This isn't problem of gnome shell because it works with other players. I tried in ubuntu 16.04 and ubuntu gnome 16.04 and linux mint without any successful result.

**Comment by emersion** [comment] 2017-08-24 20:50
>i can't send any metadata

What do you mean?

If possible, provide your source code and describe what happens and what is expected to happen.

**Comment by MarcosPer** [comment] 2017-08-28 11:03
For example when i use examples/player.js i see this in status bar

![captura de pantalla de 2017-08-28 12-48-45](https://user-images.githubusercontent.com/19536941/29770570-0d5faeb6-8bf0-11e7-93c9-c60590b14c63.png)

Events work great but i don't see any metadata info as title for example. But when i use other player i see metadata correctly so insn't problem of status bar

![captura de pantalla de 2017-08-28 12-56-55](https://user-images.githubusercontent.com/19536941/29770670-6e16fc28-8bf0-11e7-8216-b6548bc8c3bf.png)

I think that is a problem of the way that dbus send metadata, but its only an suspicion but i didn't found any evidence of this.

**Comment by fcastilloec** [comment] 2017-11-07 20:48
You shouldn't rely on the example because the art URL used is not working anymore and there's an error on the artist metadata.
Try again the example, and replace:

- `'mpris:artUrl': https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Adele_2016.jpg/800px-Adele_2016.jpg`
- `'xesam:artist': ['Adele']`

Notice that the `'xesam:artist'` is an array an not a string. Try both of this and the example should work.

**Comment by acrisci** [comment] 2019-03-05 03:51
I'm pretty sure this should work now with the dbus-next update.

**Comment by emersion** [comment] 2019-03-05 08:49
Yeah. I'm going to close this as the code has completely changed. Feel free to re-open if you can still reproduce.

**Closed by emersion** 2019-03-05 08:49 UTC
Labels: bug
